export const ALL_NUTRIENTS = [
  // Common
  { key: "calories", display_name: "Calories", unit: "kcal" },
  { key: "protein", display_name: "Protein", unit: "g" },
  { key: "total_fat", display_name: "Total Fat", unit: "g" },
  { key: "saturated_fat", display_name: "Saturated Fat", unit: "g" },
  { key: "trans_fat", display_name: "Trans Fat", unit: "g" },
  { key: "total_carbs", display_name: "Total Carbs", unit: "g" },
  { key: "dietary_fiber", display_name: "Dietary Fiber", unit: "g" },
  { key: "sugars", display_name: "Sugars", unit: "g" },
  { key: "added_sugars", display_name: "Added Sugars", unit: "g" },
  { key: "cholesterol", display_name: "Cholesterol", unit: "mg" },
  { key: "sodium", display_name: "Sodium", unit: "mg" },
  { key: "potassium", display_name: "Potassium", unit: "mg" },
  { key: "vitamin_d", display_name: "Vitamin D", unit: "mcg" },
  { key: "calcium", display_name: "Calcium", unit: "mg" },
  { key: "iron", display_name: "Iron", unit: "mg" },
  { key: "vitamin_a", display_name: "Vitamin A", unit: "mcg" },
  { key: "vitamin_c", display_name: "Vitamin C", unit: "mg" },

  // Niche - Fats
  {
    key: "polyunsaturated_fat",
    display_name: "Polyunsaturated Fat",
    unit: "g",
  },
  {
    key: "monounsaturated_fat",
    display_name: "Monounsaturated Fat",
    unit: "g",
  },

  // Niche - Fiber
  { key: "soluble_fiber", display_name: "Soluble Fiber", unit: "g" },
  { key: "insoluble_fiber", display_name: "Insoluble Fiber", unit: "g" },
  { key: "sugar_alcohols", display_name: "Sugar Alcohols", unit: "g" },

  // Niche - Vitamins
  { key: "vitamin_e", display_name: "Vitamin E", unit: "mg" },
  { key: "vitamin_k", display_name: "Vitamin K", unit: "mcg" },
  { key: "thiamin", display_name: "Thiamin (B1)", unit: "mg" },
  { key: "riboflavin", display_name: "Riboflavin (B2)", unit: "mg" },
  { key: "niacin", display_name: "Niacin (B3)", unit: "mg" },
  { key: "vitamin_b6", display_name: "Vitamin B6", unit: "mg" },
  { key: "folate", display_name: "Folate", unit: "mcg" },
  { key: "vitamin_b12", display_name: "Vitamin B12", unit: "mcg" },
  { key: "biotin", display_name: "Biotin", unit: "mcg" },
  { key: "pantothenic_acid", display_name: "Pantothenic Acid", unit: "mg" },

  // Niche - Minerals
  { key: "phosphorus", display_name: "Phosphorus", unit: "mg" },
  { key: "iodine", display_name: "Iodine", unit: "mcg" },
  { key: "magnesium", display_name: "Magnesium", unit: "mg" },
  { key: "zinc", display_name: "Zinc", unit: "mg" },
  { key: "selenium", display_name: "Selenium", unit: "mcg" },
  { key: "copper", display_name: "Copper", unit: "mg" },
  { key: "manganese", display_name: "Manganese", unit: "mg" },
  { key: "chromium", display_name: "Chromium", unit: "mcg" },
  { key: "molybdenum", display_name: "Molybdenum", unit: "mcg" },
  { key: "chloride", display_name: "Chloride", unit: "mg" },

  // Niche - Amino Acids
  { key: "tryptophan", display_name: "Tryptophan", unit: "mg" },
  { key: "threonine", display_name: "Threonine", unit: "mg" },
  { key: "isoleucine", display_name: "Isoleucine", unit: "mg" },
  { key: "leucine", display_name: "Leucine", unit: "mg" },
  { key: "lysine", display_name: "Lysine", unit: "mg" },
  { key: "methionine", display_name: "Methionine", unit: "mg" },
  { key: "cystine", display_name: "Cystine", unit: "mg" },
  { key: "phenylalanine", display_name: "Phenylalanine", unit: "mg" },
  { key: "tyrosine", display_name: "Tyrosine", unit: "mg" },
  { key: "valine", display_name: "Valine", unit: "mg" },
  { key: "arginine", display_name: "Arginine", unit: "mg" },
  { key: "histidine", display_name: "Histidine", unit: "mg" },
  { key: "alanine", display_name: "Alanine", unit: "mg" },
  { key: "aspartic_acid", display_name: "Aspartic Acid", unit: "mg" },
  { key: "glutamic_acid", display_name: "Glutamic Acid", unit: "mg" },
  { key: "glycine", display_name: "Glycine", unit: "mg" },
  { key: "proline", display_name: "Proline", unit: "mg" },
  { key: "serine", display_name: "Serine", unit: "mg" },
];

export const ALL_NUTRIENTS_DICT: Record<
  string,
  { display_name: string; unit: string }
> = {
  calories: { display_name: "Calories", unit: "kcal" },
  protein: { display_name: "Protein", unit: "g" },
  total_fat: { display_name: "Total Fat", unit: "g" },
  saturated_fat: { display_name: "Saturated Fat", unit: "g" },
  trans_fat: { display_name: "Trans Fat", unit: "g" },
  total_carbs: { display_name: "Total Carbs", unit: "g" },
  dietary_fiber: { display_name: "Dietary Fiber", unit: "g" },
  sugars: { display_name: "Sugars", unit: "g" },
  added_sugars: { display_name: "Added Sugars", unit: "g" },
  cholesterol: { display_name: "Cholesterol", unit: "mg" },
  sodium: { display_name: "Sodium", unit: "mg" },
  potassium: { display_name: "Potassium", unit: "mg" },
  vitamin_d: { display_name: "Vitamin D", unit: "mcg" },
  calcium: { display_name: "Calcium", unit: "mg" },
  iron: { display_name: "Iron", unit: "mg" },
  vitamin_a: { display_name: "Vitamin A", unit: "mcg" },
  vitamin_c: { display_name: "Vitamin C", unit: "mg" },
  polyunsaturated_fat: { display_name: "Polyunsaturated Fat", unit: "g" },
  monounsaturated_fat: { display_name: "Monounsaturated Fat", unit: "g" },
  soluble_fiber: { display_name: "Soluble Fiber", unit: "g" },
  insoluble_fiber: { display_name: "Insoluble Fiber", unit: "g" },
  sugar_alcohols: { display_name: "Sugar Alcohols", unit: "g" },
  vitamin_e: { display_name: "Vitamin E", unit: "mg" },
  vitamin_k: { display_name: "Vitamin K", unit: "mcg" },
  thiamin: { display_name: "Thiamin (B1)", unit: "mg" },
  riboflavin: { display_name: "Riboflavin (B2)", unit: "mg" },
  niacin: { display_name: "Niacin (B3)", unit: "mg" },
  vitamin_b6: { display_name: "Vitamin B6", unit: "mg" },
  folate: { display_name: "Folate", unit: "mcg" },
  vitamin_b12: { display_name: "Vitamin B12", unit: "mcg" },
  biotin: { display_name: "Biotin", unit: "mcg" },
  pantothenic_acid: { display_name: "Pantothenic Acid", unit: "mg" },
  phosphorus: { display_name: "Phosphorus", unit: "mg" },
  iodine: { display_name: "Iodine", unit: "mcg" },
  magnesium: { display_name: "Magnesium", unit: "mg" },
  zinc: { display_name: "Zinc", unit: "mg" },
  selenium: { display_name: "Selenium", unit: "mcg" },
  copper: { display_name: "Copper", unit: "mg" },
  manganese: { display_name: "Manganese", unit: "mg" },
  chromium: { display_name: "Chromium", unit: "mcg" },
  molybdenum: { display_name: "Molybdenum", unit: "mcg" },
  chloride: { display_name: "Chloride", unit: "mg" },
  tryptophan: { display_name: "Tryptophan", unit: "mg" },
  threonine: { display_name: "Threonine", unit: "mg" },
  isoleucine: { display_name: "Isoleucine", unit: "mg" },
  leucine: { display_name: "Leucine", unit: "mg" },
  lysine: { display_name: "Lysine", unit: "mg" },
  methionine: { display_name: "Methionine", unit: "mg" },
  cystine: { display_name: "Cystine", unit: "mg" },
  phenylalanine: { display_name: "Phenylalanine", unit: "mg" },
  tyrosine: { display_name: "Tyrosine", unit: "mg" },
  valine: { display_name: "Valine", unit: "mg" },
  arginine: { display_name: "Arginine", unit: "mg" },
  histidine: { display_name: "Histidine", unit: "mg" },
  alanine: { display_name: "Alanine", unit: "mg" },
  aspartic_acid: { display_name: "Aspartic Acid", unit: "mg" },
  glutamic_acid: { display_name: "Glutamic Acid", unit: "mg" },
  glycine: { display_name: "Glycine", unit: "mg" },
  proline: { display_name: "Proline", unit: "mg" },
  serine: { display_name: "Serine", unit: "mg" },
};
